services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
      - keycloak
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM=personal-cloud
      - REACT_APP_KEYCLOAK_CLIENT_ID=frontend-client

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - api_uploads:/usr/src/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/personal_cloud
      - JWT_SECRET=your_jwt_secret
      - QUOTA_LIMIT=5GB
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=personal-cloud
      - KEYCLOAK_CLIENT_ID=frontend-client
      - KC_SPI_CONTENT_SECURITY_POLICY_FRAME_SRC=frame-src 'self' http://localhost:3000;
      - KC_SPI_CONTENT_SECURITY_POLICY_FRAME_ANCESTORS=frame-ancestors 'self' http://localhost:3000;
    depends_on:
      - mongo
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HEALTH_ENABLED=true
    command: start-dev
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  postgres_data:
  keycloak_data:
  api_uploads: