services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - api
      - keycloak
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_KEYCLOAK_URL=${REACT_APP_KEYCLOAK_URL}
      - REACT_APP_KEYCLOAK_REALM=${REACT_APP_KEYCLOAK_REALM}
      - REACT_APP_KEYCLOAK_CLIENT_ID=${REACT_APP_KEYCLOAK_CLIENT_ID}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:5000"
    volumes:
      - api_uploads:/usr/src/app/uploads
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - QUOTA_LIMIT=${QUOTA_LIMIT}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KC_SPI_CONTENT_SECURITY_POLICY_FRAME_SRC=${KC_SPI_CONTENT_SECURITY_POLICY_FRAME_SRC}
      - KC_SPI_CONTENT_SECURITY_POLICY_FRAME_ANCESTORS=${KC_SPI_CONTENT_SECURITY_POLICY_FRAME_ANCESTORS}
    depends_on:
      - mongo
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HEALTH_ENABLED=true
    command: start-dev
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  postgres_data:
  keycloak_data:
  api_uploads: